# Generated by Django 4.2
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="CalculationTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bloodlosscalc_id", models.IntegerField()),
                ("operation_id", models.IntegerField()),
                ("patient_height", models.FloatField()),
                ("patient_weight", models.IntegerField()),
                ("hb_before", models.IntegerField(blank=True, null=True)),
                ("hb_after", models.IntegerField(blank=True, null=True)),
                ("surgery_duration", models.FloatField(blank=True, null=True)),
                ("blood_loss_coeff", models.FloatField()),
                ("avg_blood_loss", models.IntegerField()),
                ("total_blood_loss", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(choices=[
                    ("PENDING", "Ожидает расчета"),
                    ("PROCESSING", "В процессе"),
                    ("COMPLETED", "Завершено"),
                    ("FAILED", "Ошибка")
                ], default="PENDING", max_length=20)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]